version: '3.8'

services:
  coturn:
    image: coturn/coturn:4.6.2-r8
    container_name: coturn-server
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./coturn/coturn.conf:/etc/coturn/turnserver.conf:ro
      - ./certs:/etc/coturn/certs:ro
      - coturn_logs:/var/log/coturn
    command: ["-c", "/etc/coturn/turnserver.conf"]
    # ports:
    #   - "3478:3478/tcp"
    #   - "3478:3478/udp" 
    #   - "5349:5349/tcp"
    #   - "5349:5349/udp"
    #   - "49152-65535:49152-65535/udp"  # RTP port range

volumes:
  coturn_logs:
    driver: local